version: 2.1
jobs:
  initialize: # Initialize review app on pr
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - restore_cache: # Note: Delete cache manually by updating CACHE_VERSION in Project Settings.
          key: deps1-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum ".review-apps/ci-requirements.txt" }}
      - run:
          name: Install python dependencies in virtual environment
          command: |
            cd .review-apps/
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r ci-requirements.txt
      - run:
          name: Run Initialize command
          command: |
            cd .review-apps/
            env
            source venv/bin/activate
            python3 initialize.py
      - save_cache:
          key: deps1-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum ".review-apps/ci-requirements.txt" }}
          paths:
            - "venv"
  deploy: # Deploy code to main app on merge
    docker: 
      - image: cimg/python:3.6
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - restore_cache:
          key: deps1-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum ".review-apps/ci-requirements.txt" }}
      - run:
          name: Install python dependencies in virtual environment
          command: |
            cd .review-apps/
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r ci-requirements.txt
      - run:
          name: Run Deploy Command
          command: |
            cd .review-apps/
            env
            source venv/bin/activate
            python3 deploy.py
      - save_cache:
          key: deps1-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum ".review-apps/ci-requirements.txt" }}
          paths:
            - "venv"
  delete: # Delete old review apps on schedule
    docker: 
      - image: cimg/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps2-{{ .Branch }}-{{ checksum ".review-apps/ci-requirements.txt" }}
      - run:
          name: Install python dependencies in a virtual environment
          command: |
            cd .review-apps/
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r ci-requirements.txt
      - run:
          name: Run Delete Command 
          command: |
            cd .review-apps/
            env
            source venv/bin/activate
            python3 delete.py
      - save_cache:
          key: deps2-{{ .Branch }}-{{ checksum ".review-apps/ci-requirements.txt" }}
          paths:
            - "venv"

workflows:
  deploy-workflow: # Initializes and deploys Review App on commit
    jobs:
      - initialize:
          name: initialize-review-app
          filters:
            branches:
              ignore:
                - main
      - deploy:
          name: deploy-review-app
          requires:
            - initialize-review-app
          filters:
            branches:
              ignore:
                - main
      - deploy:
          name: deploy-main-app
          filters:
            branches:
              only:
                - main
  delete-workflow:
    triggers:
      - schedule:
          cron: "0 0 * * 1-5" # At midnight from Monday through Friday.
          filters:
            branches:
              ignore:
                - main
    jobs:
      - delete

