version: 2.1
jobs:
  deploy:
    docker: 
      - image: cimg/python:3.6
    steps:
      - checkout # checkout code in project directory
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "ci-requirements.txt" }}
      - run:
          name: Install python dependencies in virtual environment
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r ci-requirements.txt
      - run:
          name: Run Deploy Command
          command: |
            env
            source venv/bin/activate
            python3 app_manager.py aa-chris
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "ci-requirements.txt" }}
          paths:
            - "venv"

  delete:
    docker: 
      - image: cimg/python:3.6
    steps:
      - checkout # checkout code in project directory
      - restore_cache:
          key: deps2-{{ .Branch }}-{{ checksum "ci-requirements.txt" }}
      - run:
          name: Install python dependencies in a virtual environment
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r ci-requirements.txt
      - run:
          name: Run Delete Command 
          command: |
            env
            echo "Deleting expired review apps..."
            source venv/bin/activate
            python3 delete.py review-app- 5
      - save_cache:
          key: deps2-{{ .Branch }}-{{ checksum "ci-requirements.txt" }}
          paths:
            - "venv"
workflows:
  commit-workflow:
    jobs:
      - deploy
  schedule-workflow:
    triggers:
      - schedule:
          cron: "1,10,20,30,40,50 0 * * * *" # every 5 minutes
          # cron: "5,10,15,20,25,30 0 * * * 1-5" # 00:00 mon-fri
          filters:
            branches:
              only: 
                - tngo-graphql-demo
    jobs:
    - delete