version: 2.1
jobs:
  initialize: # Initialize review app when PR is created
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - restore_cache: # Note: Delete cache manually by updating CACHE_VERSION in Project Settings.
          key: deps1-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum ".circleci/ci-requirements.txt" }}
      - run:
          name: Install python dependencies in virtual environment
          command: |
            cd .circleci/
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r ci-requirements.txt
      - run:
          name: Run Initialize command
          command: |
            cd .circleci/
            env
            source venv/bin/activate
            python3 initialize.py
      - save_cache:
          key: deps1-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum ".circleci/ci-requirements.txt" }}
          paths:
            - "venv"
  
  deploy: # Deploy the code to the target app
    docker: 
      - image: cimg/python:3.6
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - restore_cache:
          key: deps1-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum ".circleci/ci-requirements.txt" }}
      - run:
          name: Install python dependencies in virtual environment
          command: |
            cd .circleci/
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r ci-requirements.txt
      - run:
          name: Run Deploy Command
          command: |
            cd .circleci/
            env
            source venv/bin/activate
            python3 deploy.py
      - save_cache:
          key: deps1-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum ".circleci/ci-requirements.txt" }}
          paths:
            - "venv"

  delete: # Delete old review apps on a schedule
    docker: 
      - image: cimg/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps2-{{ .Branch }}-{{ checksum ".circleci/ci-requirements.txt" }}
      - run:
          name: Install python dependencies in a virtual environment
          command: |
            cd .circleci/
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r ci-requirements.txt
      - run:
          name: Run Delete Command 
          command: |
            cd .circleci/
            env
            echo "Deleting expired review apps and databases..."
            source venv/bin/activate
            python3 delete.py
      - save_cache:
          key: deps2-{{ .Branch }}-{{ checksum ".circleci/ci-requirements.txt" }}
          paths:
            - "venv"
workflows:
  deploy-workflow:
    jobs:
      - deploy:
          requires:
            - initialize
          filters:
            branches:
              ignore:
                - main
  merge-workflow:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
  schedule-workflow:
    triggers:
      - schedule:
          cron: "0 0 * * 1-5" # At midnight from Monday through Friday.
          filters:
            branches:
              ignore:
                - main
    jobs:
      - delete