version: 2.1

workflows:
  # Initializes and deploys Review App on commit
  deploy-workflow:
    jobs:
      - lint:
          name: pre-deploy
      - initialize:
          name: initialize-review-app
          requires:
            - pre-deploy
          filters:
            branches:
              ignore:
                - main   
      - deploy:
          name: deploy-review-app
          requires:
            - initialize-review-app
          filters:
            branches:
              ignore:
                - main
      - deploy:
          name: deploy-main-app
          filters:
            branches:
              only:
                - main
  # Deletes stale Review Apps on a schedule
  # At midnight from Monday through Friday.
  delete-workflow:
    triggers:
      - schedule:
          cron: "0 0 * * 1-5"
          filters:
            branches:
              ignore:
                - main
    jobs:
      - delete

jobs:

  # Lint Dash app file
  lint: 
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      # Note: Add CACHE_VERSION as an environment variable. Delete cache
      # manually by updating CACHE_VERSION in Project Settings.
      - restore_cache:
          key: deps1-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum ".review-apps/ci-requirements.txt" }}
      - run:
          name: black
          command: |
            pip install black==19.10b0 --quiet
            black --check -l 79 app.py
      - run:
          name: flake8
          command: |
            pip install flake8 pep8-naming --quiet
            flake8 app.py

  # Initialize Review App on pr commit
  initialize: 
    docker:
      - image: cimg/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - restore_cache: 
          key: deps1-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum ".review-apps/ci-requirements.txt" }}
      - run:
          name: Install python dependencies in virtual environment
          command: |
            cd .review-apps/
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r ci-requirements.txt --quiet
      - run:
          name: Run Initialize command
          command: |
            cd .review-apps/
            env
            source venv/bin/activate
            python3 initialize.py
      - save_cache:
          key: deps1-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum ".review-apps/ci-requirements.txt" }}
          paths:
            - "venv"

   # Deploy code to main app on merge
  deploy:
    docker: 
      - image: cimg/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - restore_cache:
          key: deps1-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum ".review-apps/ci-requirements.txt" }}
      - run:
          name: Install python dependencies in virtual environment
          command: |
            cd .review-apps/
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r ci-requirements.txt --quiet
      - run:
          name: Run Deploy Command
          command: |
            cd .review-apps/
            env
            source venv/bin/activate
            python3 deploy.py
      - save_cache:
          key: deps1-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum ".review-apps/ci-requirements.txt" }}
          paths:
            - "venv"

  # Delete old review apps on schedule
  delete:
    docker: 
      - image: cimg/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: deps2-{{ .Branch }}-{{ checksum ".review-apps/ci-requirements.txt" }}
      - run:
          name: Install python dependencies in a virtual environment
          command: |
            cd .review-apps/
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r ci-requirements.txt --quiet
      - run:
          name: Run Delete Command 
          command: |
            cd .review-apps/
            env
            source venv/bin/activate
            python3 delete.py
      - save_cache:
          key: deps2-{{ .Branch }}-{{ checksum ".review-apps/ci-requirements.txt" }}
          paths:
            - "venv"