version: 2.1
jobs:
  deploy:
    docker: 
      - image: cimg/python:3.6 # main container where this container's job are run
    steps:
      - checkout # checkout code in project directory
      - run:
          name: Install python dependencies in virtual environment
          command: |
            pip install --upgrade pip
            python3 -m venv venv
            source .venv/bin/activate
            pip install -r ci-requirements.txt
      - run:
          name: Run Deploy Command
          command: |
            python3 app_manager.py aa-chris
       

  delete:
    docker: 
      - image: cimg/python:3.6 # main container where this container's job are run
    steps:
      - checkout # checkout code in project directory
      - restore_cache:
      - run:
          name: Install python dependencies in a virtual environment
          command: |
            pip install -r ci-requirements.txt
            
      - run:
          name: Run Delete Command 
          command: |
            echo "Deleting expired review apps..."
            python3 delete.py review-app- 0

          
workflows:
  commit-workflow:
    jobs:
      - deploy
  schedule-workflow:
    triggers:
      - schedule:
          cron: "5-59 * * * *" # every minute
          # cron: "0 0 * * 1-5" # 00:00 mon-fri
          filters:
            branches:
              only: 
                - tngo-graphql-demo
    jobs:
    - delete
